var data = [[
{key: "d", category: "Node", color: "orange"},
{key: "e", category: "Node", color: "orange"},
{key: "f", category: "Node", color: "orange"},
{key: "d_I1", category: "JoinNode", color: "pink"},
{key: "f_O", category: "BranchNode", color: "cyan"},
{key: "a_O1", category: "ForkNode", color: "red"},
{key: "c", category: "Node", color: "orange"},
{key: "e_I1", category: "JoinNode", color: "pink"},
{key: "f_O1", category: "ForkNode", color: "red"},
{key: "a_O", category: "BranchNode", color: "cyan"},
{key: "b_O", category: "BranchNode", color: "cyan"},
{key: "b", category: "Node", color: "orange"},
{key: "a", category: "Node", color: "orange"},
{key: "c_O", category: "BranchNode", color: "cyan"},
{key: "start", category: "InitialNode", color: "black"},
{key: "end", category: "FinalNode", color: "black"},
{key: "BranchInd", category: "BranchNode", color: "cyan"},
{key: "BranchIne", category: "BranchNode", color: "cyan"},
{key: "BranchInc", category: "BranchNode", color: "cyan"},
{key: "BranchInb", category: "BranchNode", color: "cyan"}
],
[
{from: "d", to: "end"},
{from: "start", to: "a"},
{from: "c", to: "c_O"},
{from: "a", to: "a_O"},
{from: "a_O", to: "a_O1"},
{from: "b", to: "b_O"},
{from: "f", to: "f_O"},
{from: "f_O", to: "f_O1"},
{from: "c_O", to: "d_I1"},
{from: "c_O", to: "e_I1"},
{from: "e", to: "f"},
{from: "b_O", to: "d_I1"},
{from: "b_O", to: "e_I1"},
{from: "f_O", to: "BranchInc"},
{from: "a_O1", to: "BranchInc"},
{from: "f_O1", to: "BranchInc"},
{from: "a_O", to: "BranchInc"},
{from: "d_I1", to: "BranchInd"},
{from: "b_O", to: "BranchInd"},
{from: "a_O1", to: "BranchInb"},
{from: "f_O1", to: "BranchInb"},
{from: "e_I1", to: "BranchIne"},
{from: "b_O", to: "BranchIne"},
{from: "BranchInd", to: "d"},
{from: "BranchIne", to: "e"},
{from: "BranchInc", to: "c"},
{from: "BranchInb", to: "b"}
]]