var data = [

[
{key: "([Investigate software|15045],[Write report|15099])", category: "Node", color: "orange"},
{key: "First line support|3268", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|7513", category: "Node", color: "orange"},
{key: "Modifica richiesta attrezzatura|52577", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|15183", category: "Node", color: "orange"},
{key: "Review profitability|3775", category: "Node", color: "orange"},
{key: "Investigate hardware|3862", category: "Node", color: "orange"},
{key: "Investigate software|15045", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5080", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|5099],[Rifiuta la richiesta|5110])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50134],[Check diponibilità|50145])", category: "Node", color: "orange"},
{key: "([Rifiuta la richiesta|5161],[Processo Richiesta di Vacanza|5169])", category: "Node", color: "orange"},
{key: "Investigate hardware|2551", category: "Node", color: "orange"},
{key: "First line support|3083", category: "Node", color: "orange"},
{key: "([Check diponibilità|52508],[Approvazione richiesta attrezzatura|52560])", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|47547", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|52605", category: "Node", color: "orange"},
{key: "Check diponibilità|52630", category: "Node", color: "orange"},
{key: "Write report|15115", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|52560", category: "Node", color: "orange"},
{key: "([Check diponibilità|52522],[Approvazione richiesta attrezzatura|52553])", category: "Node", color: "orange"},
{key: "First line support|2982", category: "Node", color: "orange"},
{key: "([Provide new sales lead|3245],[Review profitability|3762])", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|5072", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|5161", category: "Node", color: "orange"},
{key: "Check diponibilità|52508", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|47561", category: "Node", color: "orange"},
{key: "([Check diponibilità|50145],[Approvazione richiesta attrezzatura|52538])", category: "Node", color: "orange"},
{key: "Start", category: "Node", color: "orange"},
{key: "([Investigate software|17514],[Hand over to Level 2 support|20003])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|52622],[Check diponibilità|52630])", category: "Node", color: "orange"},
{key: "([Investigate hardware|3280],[Investigate software|3283])", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|57509", category: "Node", color: "orange"},
{key: "([Investigate software|42514],[Hand over to Level 2 support|45003])", category: "Node", color: "orange"},
{key: "([Review profitability|3762],[Review customer rating|3765])", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|5271],[Rifiuta la richiesta|7513])", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50080", category: "Node", color: "orange"},
{key: "Check diponibilità|52658", category: "Node", color: "orange"},
{key: "Check diponibilità|50163", category: "Node", color: "orange"},
{key: "Hand over to Level 2 support|20003", category: "Node", color: "orange"},
{key: "Modifica richiesta attrezzatura|47542", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|47534", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50048],[Check diponibilità|50066])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|10010", category: "Node", color: "orange"},
{key: "Review profitability|3762", category: "Node", color: "orange"},
{key: "([Investigate hardware|22511],[Investigate software|22514])", category: "Node", color: "orange"},
{key: "([Approvazione richiesta attrezzatura|52546],[Modifica richiesta attrezzatura|52577])", category: "Node", color: "orange"},
{key: "([Check diponibilità|52645],[Approvazione richiesta attrezzatura|57519])", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|15198", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50108],[Check diponibilità|50119])", category: "Node", color: "orange"},
{key: "First line support|3252", category: "Node", color: "orange"},
{key: "([Check diponibilità|50031],[Approvazione richiesta attrezzatura|50039])", category: "Node", color: "orange"},
{key: "Investigate software|37514", category: "Node", color: "orange"},
{key: "Provide new sales lead|3245", category: "Node", color: "orange"},
{key: "([Rifiuta la richiesta|5243],[Processo Richiesta di Vacanza|5251])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50055],[Check diponibilità|52522])", category: "Node", color: "orange"},
{key: "Investigate software|55014", category: "Node", color: "orange"},
{key: "([Check diponibilità|50066],[Approvazione richiesta attrezzatura|57548])", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50134", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50006],[Check diponibilità|52508])", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|50039", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|15018", category: "Node", color: "orange"},
{key: "First line support|2580", category: "Node", color: "orange"},
{key: "start", category: "InitialNode", color: "black"},
{key: "Approvazione richiesta attrezzatura|50127", category: "Node", color: "orange"},
{key: "([Check diponibilità|47526],[Approvazione richiesta attrezzatura|47534])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5209", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|5110", category: "Node", color: "orange"},
{key: "Check diponibilità|50031", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5099", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50055", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|15210],[Rifiuta la richiesta|15219])", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|5243", category: "Node", color: "orange"},
{key: "([Check diponibilità|50163],[Approvazione richiesta attrezzatura|52546])", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|15183],[Rifiuta la richiesta|15198])", category: "Node", color: "orange"},
{key: "([Check diponibilità|52630],[Approvazione richiesta attrezzatura|57509])", category: "Node", color: "orange"},
{key: "([Investigate hardware|15058],[Investigate software|15061])", category: "Node", color: "orange"},
{key: "([Investigate software|2554],[Hand over to Level 2 support|29])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|15226", category: "Node", color: "orange"},
{key: "Processo Richiesta|3949", category: "Node", color: "orange"},
{key: "Review customer rating|3778", category: "Node", color: "orange"},
{key: "Hand over to Level 2 support|29", category: "Node", color: "orange"},
{key: "([Approvazione richiesta attrezzatura|50127],[Modifica richiesta attrezzatura|52531])", category: "Node", color: "orange"},
{key: "([Investigate hardware|42511],[Investigate software|42514])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50080],[Check diponibilità|50091])", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|5133],[Rifiuta la richiesta|5161])", category: "Node", color: "orange"},
{key: "Write report|15099", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|10010],[Processo Richiesta di Vacanza|5271])", category: "Node", color: "orange"},
{key: "Investigate software|2554", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|57519", category: "Node", color: "orange"},
{key: "First line support|3291", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|52605],[Check diponibilità|52658])", category: "Node", color: "orange"},
{key: "First line support|3012", category: "Node", color: "orange"},
{key: "([Rifiuta la richiesta|15219],[Processo Richiesta di Vacanza|15226])", category: "Node", color: "orange"},
{key: "Investigate software|3865", category: "Node", color: "orange"},
{key: "Processo Richiesta|3920", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5063", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|15141],[Rifiuta la richiesta|15151])", category: "Node", color: "orange"},
{key: "Review customer rating|3765", category: "Node", color: "orange"},
{key: "([Investigate software|22514],[Hand over to Level 2 support|25003])", category: "Node", color: "orange"},
{key: "([Investigate hardware|17511],[Investigate software|17514])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5169", category: "Node", color: "orange"},
{key: "([Investigate hardware|37511],[Investigate software|37514])", category: "Node", color: "orange"},
{key: "Check diponibilità|52522", category: "Node", color: "orange"},
{key: "Hand over to Level 2 support|25003", category: "Node", color: "orange"},
{key: "First line support|3035", category: "Node", color: "orange"},
{key: "Start_O", category: "BranchNode", color: "cyan"},
{key: "([Handle escalated issue|25],[First line support|2580])", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|15219", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|5180", category: "Node", color: "orange"},
{key: "Investigate hardware|42511", category: "Node", color: "orange"},
{key: "Modifica richiesta attrezzatura|52584", category: "Node", color: "orange"},
{key: "([Modifica richiesta attrezzatura|52531],[Definizione richiesta di attrezzatura|52605])", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|52546", category: "Node", color: "orange"},
{key: "Investigate software|15061", category: "Node", color: "orange"},
{key: "Check diponibilità|50145", category: "Node", color: "orange"},
{key: "([Rifiuta la richiesta|15198],[Processo Richiesta di Vacanza|15210])", category: "Node", color: "orange"},
{key: "First line support|3005", category: "Node", color: "orange"},
{key: "Investigate hardware|15058", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|52637", category: "Node", color: "orange"},
{key: "First line support|3154", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50013", category: "Node", color: "orange"},
{key: "([Approvazione richiesta attrezzatura|52560],[Modifica richiesta attrezzatura|52591])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|47547],[Check diponibilità|47555])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5039", category: "Node", color: "orange"},
{key: "([Investigate hardware|3862],[Investigate software|3865])", category: "Node", color: "orange"},
{key: "([Investigate software|55014],[Hand over to Level 2 support|57503])", category: "Node", color: "orange"},
{key: "([Investigate hardware|2551],[Investigate software|2554])", category: "Node", color: "orange"},
{key: "First line support|3051", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|15159", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|5222],[Rifiuta la richiesta|5243])", category: "Node", color: "orange"},
{key: "Provide new sales lead|3261", category: "Node", color: "orange"},
{key: "Hand over to Level 2 support|45003", category: "Node", color: "orange"},
{key: "([Modifica richiesta attrezzatura|47542],[Definizione richiesta di attrezzatura|47547])", category: "Node", color: "orange"},
{key: "Investigate software|17514", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5133", category: "Node", color: "orange"},
{key: "([Modifica richiesta attrezzatura|52591],[Definizione richiesta di attrezzatura|52622])", category: "Node", color: "orange"},
{key: "Check diponibilità|52645", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5251", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5222", category: "Node", color: "orange"},
{key: "Investigate software|3846", category: "Node", color: "orange"},
{key: "([Investigate hardware|15042],[Investigate software|15045])", category: "Node", color: "orange"},
{key: "([Check diponibilità|52658],[Approvazione richiesta attrezzatura|57525])", category: "Node", color: "orange"},
{key: "Investigate software|22514", category: "Node", color: "orange"},
{key: "Rifiuta la richiesta|15151", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|47515", category: "Node", color: "orange"},
{key: "Modifica richiesta attrezzatura|52591", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5146", category: "Node", color: "orange"},
{key: "Check diponibilità|47555", category: "Node", color: "orange"},
{key: "First line support|3186", category: "Node", color: "orange"},
{key: "Investigate software|3283", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|52622", category: "Node", color: "orange"},
{key: "([Investigate software|37514],[Hand over to Level 2 support|40003])", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|5063],[Rifiuta la richiesta|5072])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|5271", category: "Node", color: "orange"},
{key: "([Approvazione richiesta attrezzatura|47534],[Modifica richiesta attrezzatura|47542])", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50108", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|57548", category: "Node", color: "orange"},
{key: "Investigate hardware|55011", category: "Node", color: "orange"},
{key: "([Investigate hardware|55011],[Investigate software|55014])", category: "Node", color: "orange"},
{key: "Check diponibilità|50066", category: "Node", color: "orange"},
{key: "([Approvazione richiesta attrezzatura|52553],[Modifica richiesta attrezzatura|52584])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|52637],[Check diponibilità|52645])", category: "Node", color: "orange"},
{key: "First line support|3115", category: "Node", color: "orange"},
{key: "([Check diponibilità|50091],[Approvazione richiesta attrezzatura|52598])", category: "Node", color: "orange"},
{key: "Hand over to Level 2 support|40003", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50013],[Check diponibilità|50031])", category: "Node", color: "orange"},
{key: "Handle escalated issue|25", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50152", category: "Node", color: "orange"},
{key: "([Review profitability|3775],[Review customer rating|3778])", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|52538", category: "Node", color: "orange"},
{key: "First line support|3122", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50048", category: "Node", color: "orange"},
{key: "([Provide new sales lead|3261],[Review profitability|3775])", category: "Node", color: "orange"},
{key: "Definizione richiesta di attrezzatura|50006", category: "Node", color: "orange"},
{key: "([Modifica richiesta attrezzatura|52577],[Definizione richiesta di attrezzatura|52637])", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|50152],[Check diponibilità|50163])", category: "Node", color: "orange"},
{key: "Check diponibilità|47526", category: "Node", color: "orange"},
{key: "([Definizione richiesta di attrezzatura|47515],[Check diponibilità|47526])", category: "Node", color: "orange"},
{key: "end", category: "FinalNode", color: "black"},
{key: "Processo Richiesta di Vacanza|15082", category: "Node", color: "orange"},
{key: "([Check diponibilità|50119],[Approvazione richiesta attrezzatura|50127])", category: "Node", color: "orange"},
{key: "Investigate hardware|22511", category: "Node", color: "orange"},
{key: "Investigate hardware|3843", category: "Node", color: "orange"},
{key: "Check diponibilità|50091", category: "Node", color: "orange"},
{key: "([Investigate software|15061],[Write report|15115])", category: "Node", color: "orange"},
{key: "End", category: "Node", color: "orange"},
{key: "Investigate software|42514", category: "Node", color: "orange"},
{key: "Modifica richiesta attrezzatura|52531", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|57525", category: "Node", color: "orange"},
{key: "([Investigate hardware|3843],[Investigate software|3846])", category: "Node", color: "orange"},
{key: "Check diponibilità|50119", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|52598", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|15210", category: "Node", color: "orange"},
{key: "Investigate hardware|15042", category: "Node", color: "orange"},
{key: "Investigate hardware|17511", category: "Node", color: "orange"},
{key: "Investigate hardware|37511", category: "Node", color: "orange"},
{key: "Approvazione richiesta attrezzatura|52553", category: "Node", color: "orange"},
{key: "Investigate hardware|3280", category: "Node", color: "orange"},
{key: "([Processo Richiesta di Vacanza|5169],[Rifiuta la richiesta|5180])", category: "Node", color: "orange"},
{key: "([Check diponibilità|47555],[Approvazione richiesta attrezzatura|47561])", category: "Node", color: "orange"},
{key: "Hand over to Level 2 support|57503", category: "Node", color: "orange"},
{key: "([Rifiuta la richiesta|5072],[Processo Richiesta di Vacanza|5080])", category: "Node", color: "orange"},
{key: "Processo Richiesta di Vacanza|15141", category: "Node", color: "orange"},
{key: "([Rifiuta la richiesta|15151],[Processo Richiesta di Vacanza|15159])", category: "Node", color: "orange"},
{key: "BranchInEnd", category: "BranchNode", color: "cyan"}
],
[
{from: "End", to: "end"},
{from: "start", to: "Start"},
{from: "Start", to: "Start_O"},
{from: "Rifiuta la richiesta|15198", to: "([Rifiuta la richiesta|15198],[Processo Richiesta di Vacanza|15210])"},
{from: "Investigate hardware|37511", to: "([Investigate hardware|37511],[Investigate software|37514])"},
{from: "Rifiuta la richiesta|5243", to: "([Rifiuta la richiesta|5243],[Processo Richiesta di Vacanza|5251])"},
{from: "([Definizione richiesta di attrezzatura|50006],[Check diponibilità|52508])", to: "Check diponibilità|52508"},
{from: "Start_O", to: "Investigate hardware|3843"},
{from: "Approvazione richiesta attrezzatura|50127", to: "([Approvazione richiesta attrezzatura|50127],[Modifica richiesta attrezzatura|52531])"},
{from: "([Check diponibilità|52658],[Approvazione richiesta attrezzatura|57525])", to: "Approvazione richiesta attrezzatura|57525"},
{from: "([Check diponibilità|50031],[Approvazione richiesta attrezzatura|50039])", to: "Approvazione richiesta attrezzatura|50039"},
{from: "Definizione richiesta di attrezzatura|50108", to: "([Definizione richiesta di attrezzatura|50108],[Check diponibilità|50119])"},
{from: "Rifiuta la richiesta|15151", to: "([Rifiuta la richiesta|15151],[Processo Richiesta di Vacanza|15159])"},
{from: "Start_O", to: "Provide new sales lead|3245"},
{from: "Processo Richiesta di Vacanza|15210", to: "([Processo Richiesta di Vacanza|15210],[Rifiuta la richiesta|15219])"},
{from: "([Check diponibilità|47555],[Approvazione richiesta attrezzatura|47561])", to: "Approvazione richiesta attrezzatura|47561"},
{from: "Start_O", to: "First line support|3252"},
{from: "Modifica richiesta attrezzatura|52577", to: "([Modifica richiesta attrezzatura|52577],[Definizione richiesta di attrezzatura|52637])"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5099"},
{from: "Check diponibilità|52508", to: "([Check diponibilità|52508],[Approvazione richiesta attrezzatura|52560])"},
{from: "([Rifiuta la richiesta|15151],[Processo Richiesta di Vacanza|15159])", to: "Processo Richiesta di Vacanza|15159"},
{from: "([Check diponibilità|50091],[Approvazione richiesta attrezzatura|52598])", to: "Approvazione richiesta attrezzatura|52598"},
{from: "([Rifiuta la richiesta|5243],[Processo Richiesta di Vacanza|5251])", to: "Processo Richiesta di Vacanza|5251"},
{from: "Check diponibilità|50163", to: "([Check diponibilità|50163],[Approvazione richiesta attrezzatura|52546])"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|15082"},
{from: "([Definizione richiesta di attrezzatura|50055],[Check diponibilità|52522])", to: "Check diponibilità|52522"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|47515"},
{from: "([Investigate hardware|55011],[Investigate software|55014])", to: "Investigate software|55014"},
{from: "Definizione richiesta di attrezzatura|50013", to: "([Definizione richiesta di attrezzatura|50013],[Check diponibilità|50031])"},
{from: "Review profitability|3762", to: "([Review profitability|3762],[Review customer rating|3765])"},
{from: "Provide new sales lead|3245", to: "([Provide new sales lead|3245],[Review profitability|3762])"},
{from: "Start_O", to: "Investigate hardware|17511"},
{from: "([Rifiuta la richiesta|5161],[Processo Richiesta di Vacanza|5169])", to: "Processo Richiesta di Vacanza|5169"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50152"},
{from: "Definizione richiesta di attrezzatura|52605", to: "([Definizione richiesta di attrezzatura|52605],[Check diponibilità|52658])"},
{from: "Processo Richiesta di Vacanza|5099", to: "([Processo Richiesta di Vacanza|5099],[Rifiuta la richiesta|5110])"},
{from: "Investigate software|15061", to: "([Investigate software|15061],[Write report|15115])"},
{from: "Start_O", to: "Investigate hardware|15042"},
{from: "([Investigate hardware|37511],[Investigate software|37514])", to: "Investigate software|37514"},
{from: "Approvazione richiesta attrezzatura|47534", to: "([Approvazione richiesta attrezzatura|47534],[Modifica richiesta attrezzatura|47542])"},
{from: "Processo Richiesta di Vacanza|5271", to: "([Processo Richiesta di Vacanza|5271],[Rifiuta la richiesta|7513])"},
{from: "([Definizione richiesta di attrezzatura|52637],[Check diponibilità|52645])", to: "Check diponibilità|52645"},
{from: "Definizione richiesta di attrezzatura|52622", to: "([Definizione richiesta di attrezzatura|52622],[Check diponibilità|52630])"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5146"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50006"},
{from: "([Modifica richiesta attrezzatura|52531],[Definizione richiesta di attrezzatura|52605])", to: "Definizione richiesta di attrezzatura|52605"},
{from: "([Investigate hardware|3862],[Investigate software|3865])", to: "Investigate software|3865"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50013"},
{from: "([Processo Richiesta di Vacanza|5063],[Rifiuta la richiesta|5072])", to: "Rifiuta la richiesta|5072"},
{from: "([Investigate hardware|3280],[Investigate software|3283])", to: "Investigate software|3283"},
{from: "([Investigate software|42514],[Hand over to Level 2 support|45003])", to: "Hand over to Level 2 support|45003"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|10010"},
{from: "Modifica richiesta attrezzatura|52531", to: "([Modifica richiesta attrezzatura|52531],[Definizione richiesta di attrezzatura|52605])"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5063"},
{from: "([Approvazione richiesta attrezzatura|52546],[Modifica richiesta attrezzatura|52577])", to: "Modifica richiesta attrezzatura|52577"},
{from: "([Definizione richiesta di attrezzatura|50108],[Check diponibilità|50119])", to: "Check diponibilità|50119"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|15183"},
{from: "Review profitability|3775", to: "([Review profitability|3775],[Review customer rating|3778])"},
{from: "Start_O", to: "Provide new sales lead|3261"},
{from: "Check diponibilità|50145", to: "([Check diponibilità|50145],[Approvazione richiesta attrezzatura|52538])"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50055"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|15018"},
{from: "Definizione richiesta di attrezzatura|50134", to: "([Definizione richiesta di attrezzatura|50134],[Check diponibilità|50145])"},
{from: "([Processo Richiesta di Vacanza|5133],[Rifiuta la richiesta|5161])", to: "Rifiuta la richiesta|5161"},
{from: "Start_O", to: "Processo Richiesta|3949"},
{from: "Definizione richiesta di attrezzatura|50048", to: "([Definizione richiesta di attrezzatura|50048],[Check diponibilità|50066])"},
{from: "([Definizione richiesta di attrezzatura|50013],[Check diponibilità|50031])", to: "Check diponibilità|50031"},
{from: "Start_O", to: "Processo Richiesta|3920"},
{from: "Start_O", to: "First line support|3115"},
{from: "([Check diponibilità|50066],[Approvazione richiesta attrezzatura|57548])", to: "Approvazione richiesta attrezzatura|57548"},
{from: "([Handle escalated issue|25],[First line support|2580])", to: "First line support|2580"},
{from: "Investigate hardware|2551", to: "([Investigate hardware|2551],[Investigate software|2554])"},
{from: "([Investigate software|15061],[Write report|15115])", to: "Write report|15115"},
{from: "Investigate hardware|15042", to: "([Investigate hardware|15042],[Investigate software|15045])"},
{from: "([Check diponibilità|52508],[Approvazione richiesta attrezzatura|52560])", to: "Approvazione richiesta attrezzatura|52560"},
{from: "Start_O", to: "First line support|3051"},
{from: "([Definizione richiesta di attrezzatura|47515],[Check diponibilità|47526])", to: "Check diponibilità|47526"},
{from: "Processo Richiesta di Vacanza|5063", to: "([Processo Richiesta di Vacanza|5063],[Rifiuta la richiesta|5072])"},
{from: "Modifica richiesta attrezzatura|47542", to: "([Modifica richiesta attrezzatura|47542],[Definizione richiesta di attrezzatura|47547])"},
{from: "Rifiuta la richiesta|5072", to: "([Rifiuta la richiesta|5072],[Processo Richiesta di Vacanza|5080])"},
{from: "Definizione richiesta di attrezzatura|47515", to: "([Definizione richiesta di attrezzatura|47515],[Check diponibilità|47526])"},
{from: "([Investigate hardware|17511],[Investigate software|17514])", to: "Investigate software|17514"},
{from: "Definizione richiesta di attrezzatura|47547", to: "([Definizione richiesta di attrezzatura|47547],[Check diponibilità|47555])"},
{from: "Processo Richiesta di Vacanza|5169", to: "([Processo Richiesta di Vacanza|5169],[Rifiuta la richiesta|5180])"},
{from: "Definizione richiesta di attrezzatura|52637", to: "([Definizione richiesta di attrezzatura|52637],[Check diponibilità|52645])"},
{from: "([Rifiuta la richiesta|15198],[Processo Richiesta di Vacanza|15210])", to: "Processo Richiesta di Vacanza|15210"},
{from: "Start_O", to: "First line support|3268"},
{from: "([Investigate software|15045],[Write report|15099])", to: "Write report|15099"},
{from: "([Provide new sales lead|3245],[Review profitability|3762])", to: "Review profitability|3762"},
{from: "Rifiuta la richiesta|5161", to: "([Rifiuta la richiesta|5161],[Processo Richiesta di Vacanza|5169])"},
{from: "([Definizione richiesta di attrezzatura|50134],[Check diponibilità|50145])", to: "Check diponibilità|50145"},
{from: "Approvazione richiesta attrezzatura|52553", to: "([Approvazione richiesta attrezzatura|52553],[Modifica richiesta attrezzatura|52584])"},
{from: "Modifica richiesta attrezzatura|52591", to: "([Modifica richiesta attrezzatura|52591],[Definizione richiesta di attrezzatura|52622])"},
{from: "Investigate hardware|3843", to: "([Investigate hardware|3843],[Investigate software|3846])"},
{from: "Investigate hardware|42511", to: "([Investigate hardware|42511],[Investigate software|42514])"},
{from: "Definizione richiesta di attrezzatura|50080", to: "([Definizione richiesta di attrezzatura|50080],[Check diponibilità|50091])"},
{from: "([Approvazione richiesta attrezzatura|52560],[Modifica richiesta attrezzatura|52591])", to: "Modifica richiesta attrezzatura|52591"},
{from: "([Definizione richiesta di attrezzatura|52605],[Check diponibilità|52658])", to: "Check diponibilità|52658"},
{from: "Start_O", to: "Investigate hardware|2551"},
{from: "Check diponibilità|52630", to: "([Check diponibilità|52630],[Approvazione richiesta attrezzatura|57509])"},
{from: "Start_O", to: "First line support|3083"},
{from: "Start_O", to: "First line support|3122"},
{from: "([Definizione richiesta di attrezzatura|50152],[Check diponibilità|50163])", to: "Check diponibilità|50163"},
{from: "Investigate software|55014", to: "([Investigate software|55014],[Hand over to Level 2 support|57503])"},
{from: "([Investigate hardware|3843],[Investigate software|3846])", to: "Investigate software|3846"},
{from: "([Approvazione richiesta attrezzatura|52553],[Modifica richiesta attrezzatura|52584])", to: "Modifica richiesta attrezzatura|52584"},
{from: "Processo Richiesta di Vacanza|5222", to: "([Processo Richiesta di Vacanza|5222],[Rifiuta la richiesta|5243])"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50048"},
{from: "([Modifica richiesta attrezzatura|47542],[Definizione richiesta di attrezzatura|47547])", to: "Definizione richiesta di attrezzatura|47547"},
{from: "([Processo Richiesta di Vacanza|5271],[Rifiuta la richiesta|7513])", to: "Rifiuta la richiesta|7513"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|15141"},
{from: "Definizione richiesta di attrezzatura|50006", to: "([Definizione richiesta di attrezzatura|50006],[Check diponibilità|52508])"},
{from: "([Processo Richiesta di Vacanza|15210],[Rifiuta la richiesta|15219])", to: "Rifiuta la richiesta|15219"},
{from: "([Approvazione richiesta attrezzatura|50127],[Modifica richiesta attrezzatura|52531])", to: "Modifica richiesta attrezzatura|52531"},
{from: "([Check diponibilità|50119],[Approvazione richiesta attrezzatura|50127])", to: "Approvazione richiesta attrezzatura|50127"},
{from: "([Investigate hardware|22511],[Investigate software|22514])", to: "Investigate software|22514"},
{from: "Definizione richiesta di attrezzatura|50055", to: "([Definizione richiesta di attrezzatura|50055],[Check diponibilità|52522])"},
{from: "([Rifiuta la richiesta|15219],[Processo Richiesta di Vacanza|15226])", to: "Processo Richiesta di Vacanza|15226"},
{from: "Investigate software|22514", to: "([Investigate software|22514],[Hand over to Level 2 support|25003])"},
{from: "Approvazione richiesta attrezzatura|52546", to: "([Approvazione richiesta attrezzatura|52546],[Modifica richiesta attrezzatura|52577])"},
{from: "Investigate hardware|22511", to: "([Investigate hardware|22511],[Investigate software|22514])"},
{from: "Investigate hardware|3280", to: "([Investigate hardware|3280],[Investigate software|3283])"},
{from: "([Check diponibilità|52522],[Approvazione richiesta attrezzatura|52553])", to: "Approvazione richiesta attrezzatura|52553"},
{from: "Investigate hardware|15058", to: "([Investigate hardware|15058],[Investigate software|15061])"},
{from: "([Processo Richiesta di Vacanza|5099],[Rifiuta la richiesta|5110])", to: "Rifiuta la richiesta|5110"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50108"},
{from: "Processo Richiesta di Vacanza|15141", to: "([Processo Richiesta di Vacanza|15141],[Rifiuta la richiesta|15151])"},
{from: "([Investigate hardware|42511],[Investigate software|42514])", to: "Investigate software|42514"},
{from: "([Processo Richiesta di Vacanza|5169],[Rifiuta la richiesta|5180])", to: "Rifiuta la richiesta|5180"},
{from: "([Processo Richiesta di Vacanza|5222],[Rifiuta la richiesta|5243])", to: "Rifiuta la richiesta|5243"},
{from: "Check diponibilità|50031", to: "([Check diponibilità|50031],[Approvazione richiesta attrezzatura|50039])"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50134"},
{from: "([Investigate software|37514],[Hand over to Level 2 support|40003])", to: "Hand over to Level 2 support|40003"},
{from: "([Processo Richiesta di Vacanza|15183],[Rifiuta la richiesta|15198])", to: "Rifiuta la richiesta|15198"},
{from: "Start_O", to: "First line support|3154"},
{from: "Check diponibilità|47526", to: "([Check diponibilità|47526],[Approvazione richiesta attrezzatura|47534])"},
{from: "([Definizione richiesta di attrezzatura|52622],[Check diponibilità|52630])", to: "Check diponibilità|52630"},
{from: "([Investigate software|22514],[Hand over to Level 2 support|25003])", to: "Hand over to Level 2 support|25003"},
{from: "Investigate hardware|3862", to: "([Investigate hardware|3862],[Investigate software|3865])"},
{from: "Check diponibilità|50091", to: "([Check diponibilità|50091],[Approvazione richiesta attrezzatura|52598])"},
{from: "Check diponibilità|50119", to: "([Check diponibilità|50119],[Approvazione richiesta attrezzatura|50127])"},
{from: "([Investigate hardware|15042],[Investigate software|15045])", to: "Investigate software|15045"},
{from: "Check diponibilità|50066", to: "([Check diponibilità|50066],[Approvazione richiesta attrezzatura|57548])"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5209"},
{from: "Handle escalated issue|25", to: "([Handle escalated issue|25],[First line support|2580])"},
{from: "Start_O", to: "Investigate hardware|3862"},
{from: "Start_O", to: "First line support|3035"},
{from: "Start_O", to: "Definizione richiesta di attrezzatura|50080"},
{from: "([Check diponibilità|52630],[Approvazione richiesta attrezzatura|57509])", to: "Approvazione richiesta attrezzatura|57509"},
{from: "Check diponibilità|52522", to: "([Check diponibilità|52522],[Approvazione richiesta attrezzatura|52553])"},
{from: "Investigate software|15045", to: "([Investigate software|15045],[Write report|15099])"},
{from: "Investigate software|2554", to: "([Investigate software|2554],[Hand over to Level 2 support|29])"},
{from: "Start_O", to: "Investigate hardware|22511"},
{from: "([Modifica richiesta attrezzatura|52591],[Definizione richiesta di attrezzatura|52622])", to: "Definizione richiesta di attrezzatura|52622"},
{from: "([Review profitability|3775],[Review customer rating|3778])", to: "Review customer rating|3778"},
{from: "Check diponibilità|47555", to: "([Check diponibilità|47555],[Approvazione richiesta attrezzatura|47561])"},
{from: "([Check diponibilità|50145],[Approvazione richiesta attrezzatura|52538])", to: "Approvazione richiesta attrezzatura|52538"},
{from: "Check diponibilità|52645", to: "([Check diponibilità|52645],[Approvazione richiesta attrezzatura|57519])"},
{from: "Start_O", to: "Investigate hardware|3280"},
{from: "Rifiuta la richiesta|15219", to: "([Rifiuta la richiesta|15219],[Processo Richiesta di Vacanza|15226])"},
{from: "Investigate hardware|55011", to: "([Investigate hardware|55011],[Investigate software|55014])"},
{from: "Start_O", to: "First line support|2982"},
{from: "([Definizione richiesta di attrezzatura|50080],[Check diponibilità|50091])", to: "Check diponibilità|50091"},
{from: "Start_O", to: "First line support|3186"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5039"},
{from: "([Check diponibilità|50163],[Approvazione richiesta attrezzatura|52546])", to: "Approvazione richiesta attrezzatura|52546"},
{from: "([Investigate software|55014],[Hand over to Level 2 support|57503])", to: "Hand over to Level 2 support|57503"},
{from: "Start_O", to: "Investigate hardware|42511"},
{from: "Processo Richiesta di Vacanza|10010", to: "([Processo Richiesta di Vacanza|10010],[Processo Richiesta di Vacanza|5271])"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5133"},
{from: "Start_O", to: "Handle escalated issue|25"},
{from: "Start_O", to: "Processo Richiesta di Vacanza|5222"},
{from: "([Investigate hardware|15058],[Investigate software|15061])", to: "Investigate software|15061"},
{from: "([Check diponibilità|52645],[Approvazione richiesta attrezzatura|57519])", to: "Approvazione richiesta attrezzatura|57519"},
{from: "Check diponibilità|52658", to: "([Check diponibilità|52658],[Approvazione richiesta attrezzatura|57525])"},
{from: "Processo Richiesta di Vacanza|5133", to: "([Processo Richiesta di Vacanza|5133],[Rifiuta la richiesta|5161])"},
{from: "([Processo Richiesta di Vacanza|10010],[Processo Richiesta di Vacanza|5271])", to: "Processo Richiesta di Vacanza|5271"},
{from: "([Definizione richiesta di attrezzatura|47547],[Check diponibilità|47555])", to: "Check diponibilità|47555"},
{from: "([Investigate hardware|2551],[Investigate software|2554])", to: "Investigate software|2554"},
{from: "Provide new sales lead|3261", to: "([Provide new sales lead|3261],[Review profitability|3775])"},
{from: "Definizione richiesta di attrezzatura|50152", to: "([Definizione richiesta di attrezzatura|50152],[Check diponibilità|50163])"},
{from: "Start_O", to: "First line support|3012"},
{from: "([Modifica richiesta attrezzatura|52577],[Definizione richiesta di attrezzatura|52637])", to: "Definizione richiesta di attrezzatura|52637"},
{from: "Investigate software|17514", to: "([Investigate software|17514],[Hand over to Level 2 support|20003])"},
{from: "([Processo Richiesta di Vacanza|15141],[Rifiuta la richiesta|15151])", to: "Rifiuta la richiesta|15151"},
{from: "Processo Richiesta di Vacanza|15183", to: "([Processo Richiesta di Vacanza|15183],[Rifiuta la richiesta|15198])"},
{from: "Start_O", to: "Investigate hardware|37511"},
{from: "Start_O", to: "First line support|3291"},
{from: "([Definizione richiesta di attrezzatura|50048],[Check diponibilità|50066])", to: "Check diponibilità|50066"},
{from: "([Approvazione richiesta attrezzatura|47534],[Modifica richiesta attrezzatura|47542])", to: "Modifica richiesta attrezzatura|47542"},
{from: "Investigate software|42514", to: "([Investigate software|42514],[Hand over to Level 2 support|45003])"},
{from: "Investigate software|37514", to: "([Investigate software|37514],[Hand over to Level 2 support|40003])"},
{from: "([Check diponibilità|47526],[Approvazione richiesta attrezzatura|47534])", to: "Approvazione richiesta attrezzatura|47534"},
{from: "Start_O", to: "First line support|3005"},
{from: "([Review profitability|3762],[Review customer rating|3765])", to: "Review customer rating|3765"},
{from: "Investigate hardware|17511", to: "([Investigate hardware|17511],[Investigate software|17514])"},
{from: "([Investigate software|17514],[Hand over to Level 2 support|20003])", to: "Hand over to Level 2 support|20003"},
{from: "Start_O", to: "Investigate hardware|55011"},
{from: "Approvazione richiesta attrezzatura|52560", to: "([Approvazione richiesta attrezzatura|52560],[Modifica richiesta attrezzatura|52591])"},
{from: "([Investigate software|2554],[Hand over to Level 2 support|29])", to: "Hand over to Level 2 support|29"},
{from: "Start_O", to: "Investigate hardware|15058"},
{from: "([Rifiuta la richiesta|5072],[Processo Richiesta di Vacanza|5080])", to: "Processo Richiesta di Vacanza|5080"},
{from: "([Provide new sales lead|3261],[Review profitability|3775])", to: "Review profitability|3775"},
{from: "Investigate software|3283", to: "BranchInEnd"},
{from: "Investigate software|3865", to: "BranchInEnd"},
{from: "Processo Richiesta|3920", to: "BranchInEnd"},
{from: "First line support|3268", to: "BranchInEnd"},
{from: "Rifiuta la richiesta|7513", to: "BranchInEnd"},
{from: "Review customer rating|3765", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|5080", to: "BranchInEnd"},
{from: "Hand over to Level 2 support|25003", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|57548", to: "BranchInEnd"},
{from: "First line support|3035", to: "BranchInEnd"},
{from: "First line support|3083", to: "BranchInEnd"},
{from: "Rifiuta la richiesta|5180", to: "BranchInEnd"},
{from: "First line support|3115", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|50039", to: "BranchInEnd"},
{from: "Write report|15115", to: "BranchInEnd"},
{from: "Hand over to Level 2 support|40003", to: "BranchInEnd"},
{from: "Modifica richiesta attrezzatura|52584", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|15018", to: "BranchInEnd"},
{from: "First line support|2580", to: "BranchInEnd"},
{from: "First line support|2982", to: "BranchInEnd"},
{from: "First line support|3005", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|52538", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|5209", to: "BranchInEnd"},
{from: "Rifiuta la richiesta|5110", to: "BranchInEnd"},
{from: "First line support|3154", to: "BranchInEnd"},
{from: "First line support|3122", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|47561", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|5039", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|15082", to: "BranchInEnd"},
{from: "First line support|3051", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|57509", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|15159", to: "BranchInEnd"},
{from: "Hand over to Level 2 support|45003", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|15226", to: "BranchInEnd"},
{from: "Hand over to Level 2 support|20003", to: "BranchInEnd"},
{from: "Processo Richiesta|3949", to: "BranchInEnd"},
{from: "Review customer rating|3778", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|5251", to: "BranchInEnd"},
{from: "Hand over to Level 2 support|29", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|57525", to: "BranchInEnd"},
{from: "Investigate software|3846", to: "BranchInEnd"},
{from: "Write report|15099", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|57519", to: "BranchInEnd"},
{from: "Approvazione richiesta attrezzatura|52598", to: "BranchInEnd"},
{from: "First line support|3291", to: "BranchInEnd"},
{from: "First line support|3012", to: "BranchInEnd"},
{from: "First line support|3252", to: "BranchInEnd"},
{from: "Hand over to Level 2 support|57503", to: "BranchInEnd"},
{from: "Processo Richiesta di Vacanza|5146", to: "BranchInEnd"},
{from: "First line support|3186", to: "BranchInEnd"},
{from: "BranchInEnd", to: "End"}
]

]