var data = [[
{key: "Complete_recall_I0", category: "JoinNode", color: "pink"},
{key: "Consider_optional_actions_Prepare_to_destory_or_modify", category: "BranchNode", color: "cyan"},
{key: "Stop_production", category: "Node", color: "orange"},
{key: "Complete_optional_actions", category: "Node", color: "orange"},
{key: "Identify_remedies_O", category: "BranchNode", color: "cyan"},
{key: "Prepare_to_destory_or_modify_Complete_optional_actions", category: "BranchNode", color: "cyan"},
{key: "Prepare_to_destory_or_modify", category: "Node", color: "orange"},
{key: "Complete_optional_actions_I1", category: "JoinNode", color: "pink"},
{key: "Complete_optional_actions_I2", category: "JoinNode", color: "pink"},
{key: "Consider_optional_actions_O", category: "BranchNode", color: "cyan"},
{key: "Complete_recall", category: "Node", color: "orange"},
{key: "Complete_optional_actions_I0", category: "JoinNode", color: "pink"},
{key: "Consider_optional_actions", category: "Node", color: "orange"},
{key: "Prepare_to_destory_or_modify_I2", category: "JoinNode", color: "pink"},
{key: "EPILOGUE", category: "Node", color: "orange"},
{key: "Consider_optional_actions_O2", category: "ForkNode", color: "red"},
{key: "Arrange_disposal", category: "Node", color: "orange"},
{key: "Start_recall", category: "Node", color: "orange"},
{key: "Stop_distribution", category: "Node", color: "orange"},
{key: "PROLOGUE", category: "Node", color: "orange"},
{key: "Notify_third_parties", category: "Node", color: "orange"},
{key: "Identify_remedies", category: "Node", color: "orange"},
{key: "start", category: "InitialNode", color: "black"},
{key: "end", category: "FinalNode", color: "black"},
{key: "Stop_production_Complete_optional_actions", category: "BranchNode", color: "cyan"},
{key: "ForkStart_recall", category: "ForkNode", color: "red"},
{key: "BranchInStop_production", category: "BranchNode", color: "cyan"},
{key: "BranchInComplete_optional_actions", category: "BranchNode", color: "cyan"},
{key: "BranchInPrepare_to_destory_or_modify", category: "BranchNode", color: "cyan"},
{key: "ForkResourcesKeep_records", category: "ForkNode", color: "red"},
{key: "JoinResourcesKeep_records", category: "JoinNode", color: "pink"},
{key: "Keep_records | pippo", category: "Node", color: "orange"},
{key: "Keep_records | pluto", category: "Node", color: "orange"}
],
[
{from: "EPILOGUE", to: "end"},
{from: "start", to: "PROLOGUE"},
{from: "Consider_optional_actions", to: "Consider_optional_actions_O"},
{from: "Consider_optional_actions_O", to: "Consider_optional_actions_O2"},
{from: "Identify_remedies", to: "Identify_remedies_O"},
{from: "Consider_optional_actions_Prepare_to_destory_or_modify", to: "Prepare_to_destory_or_modify_I2"},
{from: "Complete_recall_I0", to: "Complete_recall"},
{from: "Stop_production_Complete_optional_actions", to: "Complete_optional_actions_I0"},
{from: "Stop_production_Complete_optional_actions", to: "Complete_optional_actions_I2"},
{from: "Prepare_to_destory_or_modify_Complete_optional_actions", to: "Complete_optional_actions_I0"},
{from: "Prepare_to_destory_or_modify_Complete_optional_actions", to: "Complete_optional_actions_I2"},
{from: "Complete_optional_actions", to: "Complete_recall_I0"},
{from: "Stop_distribution", to: "Complete_recall_I0"},
{from: "Arrange_disposal", to: "Complete_recall_I0"},
{from: "Stop_production", to: "Stop_production_Complete_optional_actions"},
{from: "Notify_third_parties", to: "Complete_recall_I0"},
{from: "Consider_optional_actions_O", to: "Complete_optional_actions_I1"},
{from: "PROLOGUE", to: "Start_recall"},
{from: "Complete_recall", to: "EPILOGUE"},
{from: "JoinResourcesKeep_records", to: "Complete_recall_I0"},
{from: "Consider_optional_actions_O2", to: "Consider_optional_actions_Prepare_to_destory_or_modify"},
{from: "Prepare_to_destory_or_modify", to: "Prepare_to_destory_or_modify_Complete_optional_actions"},
{from: "Identify_remedies_O", to: "Complete_optional_actions_I2"},
{from: "Identify_remedies_O", to: "Complete_optional_actions_I1"},
{from: "Identify_remedies_O", to: "Prepare_to_destory_or_modify_I2"},
{from: "Consider_optional_actions_O", to: "BranchInStop_production"},
{from: "Consider_optional_actions_O2", to: "BranchInStop_production"},
{from: "Consider_optional_actions_Prepare_to_destory_or_modify", to: "BranchInPrepare_to_destory_or_modify"},
{from: "Prepare_to_destory_or_modify_I2", to: "BranchInPrepare_to_destory_or_modify"},
{from: "Identify_remedies_O", to: "BranchInPrepare_to_destory_or_modify"},
{from: "ForkStart_recall", to: "Consider_optional_actions"},
{from: "ForkStart_recall", to: "Notify_third_parties"},
{from: "ForkStart_recall", to: "Identify_remedies"},
{from: "ForkStart_recall", to: "Arrange_disposal"},
{from: "ForkStart_recall", to: "ForkResourcesKeep_records"},
{from: "ForkStart_recall", to: "Stop_distribution"},
{from: "Complete_optional_actions_I0", to: "BranchInComplete_optional_actions"},
{from: "Complete_optional_actions_I2", to: "BranchInComplete_optional_actions"},
{from: "Complete_optional_actions_I1", to: "BranchInComplete_optional_actions"},
{from: "Start_recall", to: "ForkStart_recall"},
{from: "BranchInStop_production", to: "Stop_production"},
{from: "BranchInComplete_optional_actions", to: "Complete_optional_actions"},
{from: "BranchInPrepare_to_destory_or_modify", to: "Prepare_to_destory_or_modify"},
{from: "ForkResourcesKeep_records", to: "Keep_records | pippo"},
{from: "Keep_records | pippo", to: "JoinResourcesKeep_records"},
{from: "ForkResourcesKeep_records", to: "Keep_records | pluto"},
{from: "Keep_records | pluto", to: "JoinResourcesKeep_records"}
]]